# Numpy 应用示例

In [1]:
import numpy as np

ndarray创建

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a1 = np.zeros([3,4], dtype=np.int32)
print(a1)
print("\n" + "*"*20 +"\n")
a1 = a1.astype(np.float32)
print(a1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

********************

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [7]:
np.random.random([3,4])

array([[0.55312871, 0.68791481, 0.91312028, 0.29330055],
       [0.7325578 , 0.57874932, 0.4585525 , 0.53857596],
       [0.62800639, 0.76777484, 0.27110977, 0.01953939]])

In [8]:
np.random.randint(0, 5, [3,4])

array([[2, 1, 1, 0],
       [3, 1, 4, 2],
       [4, 0, 3, 2]])

In [9]:
np.random.normal(0, 4, [3,4])

array([[-1.38338809, -4.64064424, -2.09228263,  0.67256291],
       [-1.1170805 , -3.35347569, -1.63496266,  2.67452699],
       [ 7.98594715, -0.04871889, -0.29547544,  4.90318977]])

In [10]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
np.arange(1, 13, 2)

array([ 1,  3,  5,  7,  9, 11])

In [13]:
np.arange(1, 13, 2, dtype=np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11.], dtype=float32)

In [14]:
np.linspace(0, 100, 100, endpoint=False)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [15]:
from sklearn import datasets
iris_data = datasets.load_iris(return_X_y=True)
print(iris_data)
X,y = iris_data
np.save('iris_X', X)
np.save('iris_y', y)

(array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 

In [16]:
X = np.load('iris_X.npy')
y = np.load('iris_y.npy')
print(X,y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

对数组进行操作

In [17]:
X.shape

(150, 4)

In [18]:
X.reshape(4,-1)

array([[5.1, 3.5, 1.4, 0.2, 4.9, 3. , 1.4, 0.2, 4.7, 3.2, 1.3, 0.2, 4.6,
        3.1, 1.5, 0.2, 5. , 3.6, 1.4, 0.2, 5.4, 3.9, 1.7, 0.4, 4.6, 3.4,
        1.4, 0.3, 5. , 3.4, 1.5, 0.2, 4.4, 2.9, 1.4, 0.2, 4.9, 3.1, 1.5,
        0.1, 5.4, 3.7, 1.5, 0.2, 4.8, 3.4, 1.6, 0.2, 4.8, 3. , 1.4, 0.1,
        4.3, 3. , 1.1, 0.1, 5.8, 4. , 1.2, 0.2, 5.7, 4.4, 1.5, 0.4, 5.4,
        3.9, 1.3, 0.4, 5.1, 3.5, 1.4, 0.3, 5.7, 3.8, 1.7, 0.3, 5.1, 3.8,
        1.5, 0.3, 5.4, 3.4, 1.7, 0.2, 5.1, 3.7, 1.5, 0.4, 4.6, 3.6, 1. ,
        0.2, 5.1, 3.3, 1.7, 0.5, 4.8, 3.4, 1.9, 0.2, 5. , 3. , 1.6, 0.2,
        5. , 3.4, 1.6, 0.4, 5.2, 3.5, 1.5, 0.2, 5.2, 3.4, 1.4, 0.2, 4.7,
        3.2, 1.6, 0.2, 4.8, 3.1, 1.6, 0.2, 5.4, 3.4, 1.5, 0.4, 5.2, 4.1,
        1.5, 0.1, 5.5, 4.2, 1.4, 0.2, 4.9, 3.1, 1.5, 0.1, 5. , 3.2, 1.2,
        0.2, 5.5, 3.5, 1.3, 0.2, 4.9, 3.1],
       [1.5, 0.1, 4.4, 3. , 1.3, 0.2, 5.1, 3.4, 1.5, 0.2, 5. , 3.5, 1.3,
        0.3, 4.5, 2.3, 1.3, 0.3, 4.4, 3.2, 1.3, 0.2, 5. , 3.5, 1.6, 0.6,
       

In [19]:
X.T

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [20]:
print("Sample1:")
X[1]
print('\n' + "*" * 20 + '\n')
print("Feature 2:")
X[:,2]

Sample1:

********************

Feature 2:


array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

Numpy 运算

In [21]:
print(np.sum(X))
print(np.sum(X, axis=0))
print(np.sum(X, axis=1))

2078.2
[876.5 458.1 563.8 179.8]
[10.2  9.5  9.4  9.4 10.2 11.4  9.7 10.1  8.9  9.6 10.8 10.   9.3  8.5
 11.2 12.  11.  10.3 11.5 10.7 10.7 10.7  9.4 10.6 10.3  9.8 10.4 10.4
 10.2  9.7  9.7 10.7 10.9 11.3  9.6  9.6 10.5  9.6  8.9 10.2 10.1  8.4
  9.1 10.7 11.2  9.5 10.7  9.4 10.7  9.9 16.3 15.6 16.4 13.1 15.4 14.3
 15.9 11.6 15.4 13.2 11.5 14.6 13.2 15.1 13.4 15.6 14.6 13.6 14.4 13.1
 15.7 14.2 15.2 14.8 14.9 15.4 15.8 16.4 14.9 12.8 12.8 12.6 13.6 15.4
 14.4 15.5 16.  14.3 14.  13.3 13.7 15.1 13.6 11.6 13.8 14.1 14.1 14.7
 11.7 13.9 18.1 15.5 18.1 16.6 17.5 19.3 13.6 18.3 16.8 19.4 16.8 16.3
 17.4 15.2 16.1 17.2 16.8 20.4 19.5 14.7 18.1 15.3 19.2 15.7 17.8 18.2
 15.6 15.8 16.9 17.6 18.2 20.1 17.  15.7 15.7 19.1 17.7 16.8 15.6 17.5
 17.8 17.4 15.5 18.2 18.2 17.2 15.7 16.7 17.3 15.8]


In [22]:
X+X

array([[10.2,  7. ,  2.8,  0.4],
       [ 9.8,  6. ,  2.8,  0.4],
       [ 9.4,  6.4,  2.6,  0.4],
       [ 9.2,  6.2,  3. ,  0.4],
       [10. ,  7.2,  2.8,  0.4],
       [10.8,  7.8,  3.4,  0.8],
       [ 9.2,  6.8,  2.8,  0.6],
       [10. ,  6.8,  3. ,  0.4],
       [ 8.8,  5.8,  2.8,  0.4],
       [ 9.8,  6.2,  3. ,  0.2],
       [10.8,  7.4,  3. ,  0.4],
       [ 9.6,  6.8,  3.2,  0.4],
       [ 9.6,  6. ,  2.8,  0.2],
       [ 8.6,  6. ,  2.2,  0.2],
       [11.6,  8. ,  2.4,  0.4],
       [11.4,  8.8,  3. ,  0.8],
       [10.8,  7.8,  2.6,  0.8],
       [10.2,  7. ,  2.8,  0.6],
       [11.4,  7.6,  3.4,  0.6],
       [10.2,  7.6,  3. ,  0.6],
       [10.8,  6.8,  3.4,  0.4],
       [10.2,  7.4,  3. ,  0.8],
       [ 9.2,  7.2,  2. ,  0.4],
       [10.2,  6.6,  3.4,  1. ],
       [ 9.6,  6.8,  3.8,  0.4],
       [10. ,  6. ,  3.2,  0.4],
       [10. ,  6.8,  3.2,  0.8],
       [10.4,  7. ,  3. ,  0.4],
       [10.4,  6.8,  2.8,  0.4],
       [ 9.4,  6.4,  3.2,  0.4],
       [ 9

In [23]:
np.square(X)

array([[2.601e+01, 1.225e+01, 1.960e+00, 4.000e-02],
       [2.401e+01, 9.000e+00, 1.960e+00, 4.000e-02],
       [2.209e+01, 1.024e+01, 1.690e+00, 4.000e-02],
       [2.116e+01, 9.610e+00, 2.250e+00, 4.000e-02],
       [2.500e+01, 1.296e+01, 1.960e+00, 4.000e-02],
       [2.916e+01, 1.521e+01, 2.890e+00, 1.600e-01],
       [2.116e+01, 1.156e+01, 1.960e+00, 9.000e-02],
       [2.500e+01, 1.156e+01, 2.250e+00, 4.000e-02],
       [1.936e+01, 8.410e+00, 1.960e+00, 4.000e-02],
       [2.401e+01, 9.610e+00, 2.250e+00, 1.000e-02],
       [2.916e+01, 1.369e+01, 2.250e+00, 4.000e-02],
       [2.304e+01, 1.156e+01, 2.560e+00, 4.000e-02],
       [2.304e+01, 9.000e+00, 1.960e+00, 1.000e-02],
       [1.849e+01, 9.000e+00, 1.210e+00, 1.000e-02],
       [3.364e+01, 1.600e+01, 1.440e+00, 4.000e-02],
       [3.249e+01, 1.936e+01, 2.250e+00, 1.600e-01],
       [2.916e+01, 1.521e+01, 1.690e+00, 1.600e-01],
       [2.601e+01, 1.225e+01, 1.960e+00, 9.000e-02],
       [3.249e+01, 1.444e+01, 2.890e+00, 9.000

In [24]:
np.power(X,2)

array([[2.601e+01, 1.225e+01, 1.960e+00, 4.000e-02],
       [2.401e+01, 9.000e+00, 1.960e+00, 4.000e-02],
       [2.209e+01, 1.024e+01, 1.690e+00, 4.000e-02],
       [2.116e+01, 9.610e+00, 2.250e+00, 4.000e-02],
       [2.500e+01, 1.296e+01, 1.960e+00, 4.000e-02],
       [2.916e+01, 1.521e+01, 2.890e+00, 1.600e-01],
       [2.116e+01, 1.156e+01, 1.960e+00, 9.000e-02],
       [2.500e+01, 1.156e+01, 2.250e+00, 4.000e-02],
       [1.936e+01, 8.410e+00, 1.960e+00, 4.000e-02],
       [2.401e+01, 9.610e+00, 2.250e+00, 1.000e-02],
       [2.916e+01, 1.369e+01, 2.250e+00, 4.000e-02],
       [2.304e+01, 1.156e+01, 2.560e+00, 4.000e-02],
       [2.304e+01, 9.000e+00, 1.960e+00, 1.000e-02],
       [1.849e+01, 9.000e+00, 1.210e+00, 1.000e-02],
       [3.364e+01, 1.600e+01, 1.440e+00, 4.000e-02],
       [3.249e+01, 1.936e+01, 2.250e+00, 1.600e-01],
       [2.916e+01, 1.521e+01, 1.690e+00, 1.600e-01],
       [2.601e+01, 1.225e+01, 1.960e+00, 9.000e-02],
       [3.249e+01, 1.444e+01, 2.890e+00, 9.000

In [25]:
np.where(X[:,0]>5, X[:,0], 0)

array([5.1, 0. , 0. , 0. , 0. , 5.4, 0. , 0. , 0. , 0. , 5.4, 0. , 0. ,
       0. , 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 0. , 5.1, 0. , 0. ,
       0. , 5.2, 5.2, 0. , 0. , 5.4, 5.2, 5.5, 0. , 0. , 5.5, 0. , 0. ,
       5.1, 0. , 0. , 0. , 0. , 5.1, 0. , 5.1, 0. , 5.3, 0. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 0. , 6.6, 5.2, 0. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 0. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 0. , 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [26]:
X[:,2]>2

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,